### ISSUE TITLE
Listado de funcionalidad

### ISSUE THREAD

**Issue by dcorvetto** [pablotese/IntegracionAplicaciones#18]
1- Postear logs al backoffice por cada movimiento ... cuáles?
RTA: log de todo. Agregar un sessionBean que haga eso.
2- GET tipo de servicios (consumir y guardar en base de datos).. cuándo hacer esto?
RTA: 
3- POST usando método BO para pedir aprobación agencias
4- Proveer rest para POST estado de la solicitud y actualizar en bd
5- Mensajería de paquetes

**Comment by vguccione** [comment]
1- Postear logs al backoffice por cada movimiento ... cuáles?
2- GET tipo de servicios (consumir y guardar en base de datos).. cuándo hacer esto?
     - nosotros consumimos un REST Get que exponse BO

3- POST usando método BO para pedir aprobación agencias
    - BO tiene que exponer rest, lo invocamos por post mandando la info de la agencia nueva en allta de agencia

4- Proveer rest para POST estado de la solicitud y actualizar en bd
    -nosotros exponemos REST para que le peguen por POST, indicando cuando una agencia fue o no aprobada. Ojo, nos van a mandar el id de agencia de ellos.

5- Mensajería de paquetes
   - cuando se crea un nuevo paquete, enviar el mensaje del nuevo paquete.  (TextMessage = json) a la cola de Portal Web (a todas las colas que tengamos publicadas).
