### ISSUE TITLE
Mensajería de nuevo paquete

### ISSUE THREAD

**Issue by vguccione** [pablotese/IntegracionAplicaciones#23]
5- Mensajería de paquetes
   - cuando se crea un nuevo paquete, enviar el mensaje del nuevo paquete.  (TextMessage = json) a la cola de Portal Web (a todas las colas que tengamos publicadas de los distintos PortalesWeb).

**Comment by dcorvetto** [comment]
Usar nuevo metodo y pasar datos de paquete
