### ISSUE TITLE
¿Enviamos el paquete recién cuando se encuentra "habilitado"?

### ISSUE THREAD

**Issue by vguccione** [pablotese/IntegracionAplicaciones#48]

**Comment by vguccione** [comment]
En el form tenemos un tilde de "habilitado", y en la base una columna "estado". Si lo usamos, tendríamos que manejar también la edición para que cuando el usuario lo habilite, recién ahí se envíe.

**Comment by dcorvetto** [comment]
Diria de preguntar si agencia tiene idAgenciaBO para enviar el mensaje al crearse el paquete respectivo. Por default dejaría marcados los tildes de habilitado en los formularios
