### ISSUE TITLE
Agencias - Post nueva agencia

### ISSUE THREAD

**Issue by cricartez** [pablotese/IntegracionAplicaciones#50]
Corregir la asignación del id que viene desde el BO a cada nueva agencia. El servicio funciona bien, pero hay que deserializar el string de respuesta y extraer solamente el ID. Se estaba queriendo asignar todo el string response al idBO de la nueva agencia.

Por ahora la asignación queda comentada.

**Comment by dcorvetto** [comment]
Ya lo arreglé , hago el post desde el guardar Agencia en el EJB
